In [1]:
import numpy as np


In [5]:
# simulate probability of getting head
trials = 10000
heads = np.sum(np.random.choice(['H','T'], size=trials) == 'H')
print(heads / trials)

0.5026


In [ ]:
# Conditional Probability
A = np.array([1,1,0,1])
B = np.array([1,0,1,1])

P_A_and_B = np.sum((A==1) & (B==1)) / len(A)
P_B = np.sum(B==1) / len(B)

print(P_A_and_B / P_B)

0.6666666666666666


In [ ]:
# Bernoulli
np.random.binomial(1, 0.5, 10)

array([0, 1, 0, 1, 1, 0, 1, 0, 0, 1], dtype=int32)

In [11]:
# Binomial
np.random.binomial(10, 0.5, 100)

array([5, 4, 8, 4, 3, 5, 5, 5, 4, 3, 8, 3, 6, 6, 7, 3, 7, 7, 5, 6, 5, 5,
       6, 2, 7, 2, 4, 5, 5, 9, 5, 6, 3, 5, 3, 3, 6, 1, 4, 5, 3, 3, 4, 5,
       4, 6, 8, 4, 5, 6, 7, 5, 7, 2, 3, 2, 5, 7, 2, 6, 7, 6, 9, 8, 7, 4,
       4, 6, 7, 2, 6, 5, 3, 5, 6, 6, 5, 6, 8, 7, 5, 4, 6, 8, 2, 4, 5, 5,
       5, 6, 3, 6, 7, 6, 3, 2, 5, 3, 7, 5], dtype=int32)

In [8]:
x = np.array([1,2,3])
p = np.array([0.2,0.5,0.3])

print(np.sum(x*p))

2.0999999999999996


In [12]:
data = np.array([1,2,3,4,5])
print(np.var(data), np.std(data))

2.0 1.4142135623730951


In [13]:
# Gaussian
np.random.normal(0, 1, 1000)

array([-6.79106659e-01,  4.86472008e-01, -4.59678513e-01,  2.71598263e+00,
       -3.15838262e-01, -1.68971925e+00,  7.22732776e-01,  7.83266491e-01,
       -1.22562035e+00, -2.22811538e-01,  8.20748248e-01, -1.50653254e-01,
        9.05162000e-01, -9.95301119e-01,  1.39654692e-01,  2.28605742e-01,
        3.44536060e-01,  1.63338839e+00,  1.98286565e+00,  1.20356084e-01,
       -1.60648015e+00,  9.63528131e-01, -7.25212852e-02, -4.83345692e-01,
        7.35054131e-02,  2.58353379e-01, -2.42038736e-01, -1.68578476e+00,
        1.41317750e+00, -2.28360617e+00, -8.14839031e-03,  6.27162629e-01,
        1.59760685e+00,  3.80449459e-01, -7.47635400e-01,  6.66805322e-01,
        5.61976954e-01,  6.18831193e-02,  2.16159394e+00, -3.70883852e-02,
        5.14284378e-02, -5.53708988e-01, -1.10158475e+00, -1.86403448e-02,
        1.67822453e-01, -1.24711398e-01,  6.44954468e-01,  1.11954811e+00,
        7.55368208e-01, -5.01809727e-01, -1.73724759e+00, -4.81324696e-01,
       -5.57883044e-01, -

In [20]:
# Uniform
np.random.uniform(0, 1, 1000)

array([3.29901686e-01, 7.95883193e-01, 3.27174429e-01, 9.36359465e-01,
       5.70041293e-01, 6.76795835e-02, 2.73370127e-01, 2.57511966e-01,
       2.24856571e-01, 7.26433992e-01, 1.87388348e-01, 7.93182155e-01,
       6.30995378e-01, 9.72503244e-01, 3.92062485e-01, 6.36773705e-01,
       6.71366816e-01, 6.25155917e-01, 8.13780684e-01, 4.77691967e-01,
       5.40202450e-01, 2.11407374e-01, 4.27730868e-01, 3.89441911e-01,
       6.21089138e-01, 9.64594685e-01, 5.59723889e-01, 1.79897470e-01,
       2.37232576e-01, 8.62287603e-01, 3.93303040e-01, 7.33555501e-01,
       3.95608383e-01, 7.24399643e-01, 8.30634526e-02, 6.12839056e-01,
       7.74338283e-01, 7.60721531e-01, 2.28593428e-01, 7.59401802e-01,
       3.10081989e-01, 7.54466835e-01, 3.38159136e-01, 6.20309703e-01,
       5.32272744e-01, 1.45355993e-01, 2.51100233e-01, 4.02350424e-01,
       6.70872741e-01, 6.77991002e-01, 7.69473690e-01, 2.43627003e-01,
       7.81950930e-01, 1.25105238e-01, 4.32548239e-01, 4.19842674e-01,
      

In [18]:
# Covariance
x = np.array([1,2,3])
y = np.array([2,4,6])
print(np.cov(x,y))

[[1. 2.]
 [2. 4.]]


In [19]:
# Correlation
print(np.corrcoef(x,y))

[[1. 1.]
 [1. 1.]]


In [16]:
# Law of Large Numbers
samples = np.random.normal(0,1,10000)
print(np.mean(samples))

-0.007582557078809766


In [15]:
# Central Limit Theorem
means = [np.mean(np.random.uniform(0,1,100)) for _ in range(1000)]

In [14]:
# Maximum Likelihood Estimation (MLE)
data = np.array([1,2,3,4,5])
mu = np.mean(data)  # MLE estimate
print(mu)

3.0
