In [111]:
import numpy as np
import pandas as pd

In [112]:
df=pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [113]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [114]:
import tensorflow 
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [115]:
model=Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

c:\Users\KhushiAgarwal\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [116]:
model.summary()

Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_30 (Dense)                │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_31 (Dense)                │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [117]:
model.get_weights()


[array([[-0.547164  ,  1.1379346 ],
        [-0.372379  , -0.18329167]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.06007075],
        [-0.8596072 ]], dtype=float32),
 array([0.], dtype=float32)]

In [120]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),np.array([0.,0.],dtype=np.float32),np.array([[0.1],[0.1]],dtype=np.float32),np.array([0.],dtype=np.float32)]

In [121]:
model.set_weights(new_weights)

In [122]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [123]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [124]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 27.9165 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 27.5955 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 27.2621 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26.9319
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.5678 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.2368 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.8309 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25.4633 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.0606 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.6642 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.2814 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.8478 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.4148 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.9473 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.4709
Epoch 16/75
4/4 ━━━

In [125]:
model.get_weights()

[array([[0.37365526, 0.37365526],
        [0.36559066, 0.36559066]], dtype=float32),
 array([0.27230638, 0.27230638], dtype=float32),
 array([[0.37291545],
        [0.37291545]], dtype=float32),
 array([0.2046127], dtype=float32)]